# Generated by Django 2.2.3 on 2019-07-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellfresh', '0002_cart_comment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordernumber',
            field=models.CharField(default='000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='未支付', max_length=10),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('zip', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=11)),
                ('isdefadd', models.CharField(max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellfresh.Myuser')),
            ],
        ),
    ]
