# Generated by Django 2.2.3 on 2019-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellfresh', '0005_auto_20190716_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='oneprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
