# Generated by Django 2.2.3 on 2019-07-18 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_ads'),
        ('sellfresh', '0006_cart_oneprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods',
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellfresh.Cart'),
        ),
        migrations.CreateModel(
            name='Orderinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allprice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goodsinfo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellfresh.Order')),
            ],
        ),
    ]
