# Generated by Django 2.2.3 on 2019-07-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellfresh', '0007_auto_20190718_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allprice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
