# Generated by Django 2.2.3 on 2019-07-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernickname', models.CharField(max_length=20)),
                ('usertelephone', models.IntegerField(max_length=20)),
                ('uu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cellmall.User')),
            ],
        ),
    ]
