# Generated by Django 2.2.3 on 2019-07-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='img',
            field=models.ImageField(upload_to='ads'),
        ),
    ]
