# Generated by Django 2.2.3 on 2019-07-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190710_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Myuser'),
        ),
    ]
