# Generated by Django 2.2.3 on 2019-07-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_myuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
