# Generated by Django 2.2.3 on 2019-07-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190712_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='telephone',
            field=models.IntegerField(default=110),
        ),
    ]
