# Generated by Django 2.2.3 on 2019-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('artical', models.ForeignKey(on_delete=True, to='blog.Artical')),
            ],
        ),
    ]
