# Generated by Django 2.2.3 on 2019-07-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voteinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.CharField(choices=[('ycy', '杨超越'), ('zzy', '章子怡'), ('all', '都好看'), ('no', '都不好看')], max_length=30)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listtest.Vote1')),
            ],
        ),
        migrations.CreateModel(
            name='Votenum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosenum', models.IntegerField(max_length=30)),
                ('chooseinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listtest.Voteinfo')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listtest.Vote1')),
            ],
        ),
    ]
