# Generated by Django 2.2.3 on 2019-07-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteinfo',
            name='choose',
            field=models.CharField(choices=[('ycy', '杨超越'), ('zzy', '章子怡'), ('all', '都好看'), ('no', '都不好看')], default='ycy', max_length=30),
        ),
    ]
