# Generated by Django 2.2.3 on 2019-07-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listtest', '0002_auto_20190704_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voteinfo',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='votenum',
            name='chooseinf',
        ),
        migrations.RemoveField(
            model_name='votenum',
            name='vote',
        ),
        migrations.DeleteModel(
            name='Vote1',
        ),
        migrations.DeleteModel(
            name='Voteinfo',
        ),
        migrations.DeleteModel(
            name='Votenum',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=True, to='listtest.Question'),
        ),
    ]
