# Generated by Django 2.2.3 on 2019-07-15 12:48

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goodscontent',
            field=DjangoUeditor.models.UEditorField(),
        ),
    ]
