# Generated by Django 2.2.3 on 2019-07-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190715_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeinfo',
            name='pic',
            field=models.ImageField(null=True, upload_to='type_goods'),
        ),
    ]
